{% set name = "starlette-admin" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/starlette_admin-{{ version }}.tar.gz
  sha256: c1a295b0e7b1d828f6d131c1b1762df96b74d58ecbc0ac03f2ff720296dfbe00

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - hatchling
    - pip
    - python >=3.7
  run:
    - babel >=2.13.0
    - jinja2 >=3,<4
    - python >=3.7
    - python-multipart
    - starlette
    # These dependencies are outside contrib, as helpers, so adding them
    - markupsafe
    - pydantic

test:
  imports:
    - starlette_admin
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/starlette-admin
  summary: Fast, beautiful and extensible administrative interface framework for Starlette/FastApi applications
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/jowilf/starlette-admin

extra:
  recipe-maintainers:
    - goanpeca
    - jowilf
