{% set name = "starlette-admin" %}
{% set version = "0.15.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/starlette_admin-{{ version }}.tar.gz
  sha256: beccdb8695ecadc9f314e0b5afd2b04e067538e8273d0c3199b671198b5ee43e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - hatchling
    - pip
    - python >=3.7
  run:
    - babel >=2.13.0
    - jinja2 >=3,<4
    - python >=3.7
    - python-multipart
    - starlette
    # These dependencies are outside contrib, as helpers, so adding them
    - markupsafe
    - pydantic
    # These dependencies are optional, inside the contrib module
    # - anyio
    # - bson
    # - mongoengine
    # - pymongo
    # - sqlmodel
    # - sqlalchemy

test:
  imports:
    - starlette_admin
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/starlette-admin
  summary: Fast, beautiful and extensible administrative interface framework for Starlette/FastApi applications
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/jowilf/starlette-admin

extra:
  recipe-maintainers:
    - goanpeca
    - jowilf
